[toolchain]
# Force l'utilisation de Rust 1.88.0 pour satisfaire les dépendances (serde_with, time, etc.)
channel = "1.88.0"
# Ajoute la cible Windows 64-bit pour la compilation
targets = ["x86_64-pc-windows-msvc"]
# Installe les composants nécessaires
components = ["rust-std", "rustc", "cargo"]
